# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=75)),
                ('pub_date', models.DateField(default=datetime.datetime(2018, 3, 26, 13, 28, 4, 819434), verbose_name='Date')),
                ('publisher', models.CharField(max_length=50)),
                ('page_number', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time stamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
