# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True, verbose_name='Borrowed date')),
                ('returned_date', models.DateTimeField(auto_now=True, verbose_name='Returned')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addedOnDateTime', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addedOnDateTime', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='loginTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginToken', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('createOnDate', models.DateField(auto_now_add=True)),
                ('createAtTime', models.TimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('deactivatedOnDate', models.DateField(auto_now_add=True)),
                ('deactivatedAtTime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=75, null=True)),
                ('lname', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profileImage', models.FileField(blank=True, null=True, upload_to=b'')),
                ('password', models.CharField(max_length=100)),
                ('registeredOnDateTime', models.DateTimeField(auto_now_add=True)),
                ('registrationNumber', models.CharField(max_length=20, unique=True, verbose_name='Reg Number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Depatment')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Gender')),
            ],
        ),
        migrations.AddField(
            model_name='addbook',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 30, 11, 26, 9, 115057), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='logintokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.myUsers'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='bookDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.AddBook'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.myUsers'),
        ),
    ]
