# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180330_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='bookDetails',
            new_name='borrowedBook',
        ),
        migrations.RenameField(
            model_name='borrowbook',
            old_name='userName',
            new_name='borrower',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='borrowed_date',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='borrowedOnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='borrowedOnTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='orderedOnDate',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 3, 30, 11, 31, 55, 358823, tzinfo=utc), verbose_name='Borrowed date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='orderedOnTime',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 30, 11, 32, 5, 321657, tzinfo=utc), verbose_name='Borrowed date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 30, 11, 31, 37, 938700), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
