# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180330_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='currentToken',
            field=models.CharField(default=datetime.datetime(2018, 4, 4, 18, 35, 14, 27798, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 4, 18, 34, 57, 300512), verbose_name='Date'),
        ),
    ]
