# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180404_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 4, 18, 41, 16, 275532), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='depatment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='addedOnDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp'),
        ),
    ]
