# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180404_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time stamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 9, 54, 58, 440115), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='borrowedOnDate',
            field=models.DateField(blank=True, null=True, verbose_name='Borrowed on date'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='borrowedOnTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Borrowed on time'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='orderedOnDate',
            field=models.DateField(auto_now_add=True, verbose_name='Ordered on date'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='orderedOnTime',
            field=models.TimeField(auto_now_add=True, verbose_name='Ordered on time'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Returned date'),
        ),
        migrations.AlterField(
            model_name='depatment',
            name='addedOnDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added on'),
        ),
        migrations.AlterField(
            model_name='logintokens',
            name='deactivatedAtTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Deactivated at time'),
        ),
        migrations.AlterField(
            model_name='logintokens',
            name='deactivatedOnDate',
            field=models.DateField(auto_now_add=True, verbose_name='Deactivated on date'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='registeredOnDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered on'),
        ),
    ]
