# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180405_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='needBookOnDate',
            field=models.DateField(blank=True, null=True, verbose_name='Borrowed on date'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='needBookOnTime',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 5, 18, 28, 36, 273386, tzinfo=utc), verbose_name='Ordered on time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 18, 28, 15, 612510), verbose_name='Date'),
        ),
    ]
