# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180405_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='needBookOnDate',
            new_name='bookNeededFromDate',
        ),
        migrations.RenameField(
            model_name='borrowbook',
            old_name='needBookOnTime',
            new_name='bookNeededFromTime',
        ),
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 19, 31, 48, 431526), verbose_name='Date'),
        ),
    ]
