# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20180405_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 23, 28, 22, 35325), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='bookNeededFromDate',
            field=models.DateField(blank=True, null=True, verbose_name='book needed on'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='bookNeededFromTime',
            field=models.TimeField(auto_now_add=True, verbose_name='book needed at'),
        ),
    ]
