# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20180405_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 23, 57, 25, 350216), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='borrowedBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.AddBook', verbose_name='Book borrowed'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='returned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Returned date'),
        ),
    ]
